Completed css-three-column-layout -Kaitlin Lovrich
kaitlin-lovrich/c-0823-code-solutions pull request #35
Opened 2023-09-08 02:21 UTC by kaitlin-lovrich

![image](https://github.com/kaitlin-lovrich/c-0823-code-solutions/assets/69818777/2ae6ef4d-dd44-4445-bb00-9960c861f593)

2023-09-08 16:55 UTC, shawnkost requested changes
Some changes here Kaitlin! Another thing I noticed as well!

1. Make sure your text is centered. Compare your image to our example image. Your heading text and the text underneath the photos aren't quite aligned right

2023-09-08 16:55 UTC, shawnkost commented on css-three-column-layout/styles.css
> +  flex-wrap: wrap;
Your `.container` doesn't have `display: flex`, so this isn't doing anything, so it should be deleted

2023-09-08 16:55 UTC, shawnkost commented on css-three-column-layout/styles.css
> +  flex-direction: row; */
Delete all old code

2023-09-08 16:55 UTC, shawnkost commented on css-three-column-layout/styles.css
> +  /* flex-wrap: wrap; */
Delete all old code

2023-09-11 16:12 UTC, shawnkost requested changes
Few changes here Kaitlin!

2023-09-11 16:12 UTC, shawnkost commented on css-three-column-layout/index.html
> +            <img src="./images/merge.png" alt="" />
Needs an `alt` attribute

2023-09-11 16:12 UTC, shawnkost commented on css-three-column-layout/index.html
> +            <img src="./images/discussion.png" />
Needs an `alt` attribute

2023-09-11 16:12 UTC, shawnkost commented on css-three-column-layout/styles.css
> +  flex-wrap: wrap;
Your `.container` doesn't have `display: flex`, so this isn't doing anything, so it should be deleted

2023-09-14 00:00 UTC, kaitlin-lovrich commented
<img width="485" alt="image" src="https://github.com/kaitlin-lovrich/c-0823-code-solutions/assets/69818777/bbf4fd6f-187a-4885-9b83-51211de00135">

2023-10-15 20:09 UTC, shawnkost approved these changes
👍🏻

2023-10-16 20:35 UTC, merged